name = "irong-cc"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[vars]
VAPID_PUBLIC_KEY = "BL298TvMWFHIxNCPb1PEN5Ir8CXj0JVoqhuivoQqjbIxBLoyM_kezlWkZvQv1UtPHNiiBlQAdTyvOnPkYf4BsiY"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "IRONG_KV"
id = "0a20708bb3334ce2b737b50e6e5ac0f0"
